name: cooking_assistant
description: A cooking assistant mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 
  
  # Phone Input
  intl_phone_field: ^3.2.0
  
  # Text-to-Speech (озвучка)
  flutter_tts: ^3.8.5
  
  # Speech-to-Text (распознавание)
  speech_to_text: ^6.3.0
  
  # HTTP Requests
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true